services:
  - type: web
    name: rook-backend
    env: node
    branch: main
    root: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true

  - type: web
    name: rook-frontend
    branch: main
    root: .
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l ${PORT:-3000}
    autoDeploy: true
    envVars:
      - key: https://rook-backend.onrender.com
        value: https://rook-backend.onrender.com
